services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}    
      
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
